### ISSUE TITLE
Problem trying to access the endpoint

### ISSUE THREAD

**Issue by imetallica** [PSPDFKit-labs/bypass#27] opened 2016-08-10 20:53 UTC
Hi! I'm doing

```
  test "capture from invoice.created", %{bypass: bypass} do
    Bypass.expect bypass, fn conn ->
      assert "PUT" == conn.method
      Plug.Conn.resp(conn, 201, ~s<{"response": "ok"}>)
    end

    send_invoice(bypass.port)
  end

def send_invoice(port) do
    case HTTPoison.put("http://localhost:#{port}/", Poison.encode!(to_send)) do
      {:ok, response} -> :ok
      {:error, reason} ->
        Logger.warn "Failed to callback the invoice. Reason: #{inspect reason}."
        :error
    end
  end
```

But it's failing with this error:

```
 No HTTP request arrived at Bypass
     stacktrace:
       (bypass) lib/bypass.ex:17: anonymous fn/1 in Bypass.open/0
       (ex_unit) lib/ex_unit/on_exit_handler.ex:82: ExUnit.OnExitHandler.exec_callback/1
       (ex_unit) lib/ex_unit/on_exit_handler.ex:66: ExUnit.OnExitHandler.on_exit_runner_loop/0

```

Am I doing something wrong?

**Comment by alco** [comment] 2016-08-11 08:40
I don't see anything wrong in this code. Could you provide a minimal Mix project that reproduces the problem?

**Comment by imetallica** [comment] 2016-08-11 14:41
Sure, just clone and do the ritual `mix deps.get`, `mix test`.

https://github.com/imetallica/bypass-issue

**Comment by fastjames** [comment] 2016-10-10 18:11
I am having what appears to be the same problem, so I cloned the sample repo and I was able to replicate the problem. Also, I tried inserting a Process.sleep/0 call after bypass starts up. I grabbed the port number and verified that I was able to contact the bypass server via curl on that port. However, the sample app's test was still unable to do so.

**Comment by fastjames** [comment] 2016-10-10 20:20
I also tried swapping in HTTPoison for Gun in the tests, since my app and the sample are both using that. It did not cause any tests to fail in a way that would suggest that gun is masking a problem.

**Comment by fastjames** [comment] 2016-10-10 21:25
I noticed a small inconsistency while reading the bypass README and the tests. In the readme, it says you should use Plug.Conn.resp/3 to formulate the bypass response. However, in the test they use Plug.Conn.send_resp/3 instead. I tried changing this call in your sample app and it did not appear to change the outcome of the test, but I still wanted to make note of it.

**Comment by fastjames** [comment] 2016-10-19 21:35
After further work on this, I think my problem was compound:

1. I needed to use send_resp/3 instead of resp/3 in my bypass blocks
2. I needed to properly start one of my dependency libraries in mix.exs

After fixing those two things, I had much better results. I'll make a note to submit a pull request for the doc change I mentioned in the previous comment.

**Comment by alco** [comment] 2017-02-07 20:18
Closing this since it doesn't look like a bug in Bypass.

**Closed by alco** 2017-02-07 20:18 UTC

**Comment by nikhilmor** [comment] 2019-11-20 09:46
>     2. I needed to properly start one of my dependency libraries in mix.exs
> 
@fastjames what were the dependencies that needed to start properly.

**Comment by fastjames** [comment] 2019-11-20 17:07
> > ```
> > 2. I needed to properly start one of my dependency libraries in mix.exs
> > ```
> 
> @fastjames what were the dependencies that needed to start properly.

@nikhilmor I looked back through some of my repos, but it has been several years and I don't recall the specific dependency. Sorry I can't be of more help.

**Comment by nikhilmor** [comment] 2019-11-21 06:12
I too am facing similar issue, tried a number of things but to no avail.
