### ISSUE TITLE
spurious {:error, :eaddrinuse} with Bypass.open(port: fixed_port)

### ISSUE THREAD

**Issue by visciang** [PSPDFKit-labs/bypass#51] opened 2017-09-16 14:11 UTC
As in #31, I get `{:error, :eaddrinuse}` running a **sequential test suite** (async: false), where each test starts a Bypass listening on **the same fixed port**.

I see that in [L271](https://github.com/PSPDFKit-labs/bypass/blob/master/lib/bypass/instance.ex#L271) you try to do a sync socket close, but it seems that this is not enough, maybe the port is sync released but the underlying OS socket is still in use.

To reproduce the issue we need an async: false test suite that stress this condition, just a test like [THIS](https://github.com/PSPDFKit-labs/bypass/blob/master/test/bypass_test.exs#L41) repeated over and over till the condition happens.

I hope in the next week to find some spare time to write a test and get the error on a travis build.

**Comment by visciang** [comment] 2017-09-16 20:25
Here a test to show the issue:

[TEST](https://github.com/visciang/bypass/commit/186d7b880031d17537a52365fd55dc982fc4b0e1)
[Travis - Failed Test run](https://travis-ci.org/visciang/bypass/builds/276339542)

**Comment by MSch** [comment] 2017-09-17 12:25
Hi @visciang - thanks for the reproducible test case!

A few observations from my side: On macOS I could only seldom reproduce the test failure with 1000 iterations, so I bumped them to 10000 which made the test failure absolutely reliably for me (so far).

I've started a branch [msch/eaddrinuse](https://github.com/PSPDFKit-labs/bypass/compare/msch/eaddrinuse) where I tried to add a workaround in https://github.com/PSPDFKit-labs/bypass/commit/4ee6d9e71c1ed9c2f7950b57fe63af7c35e2618f: I connected to the (supposedly) closed port immediately after closing it - this always failed, as expected, but the error kept happening, until I bumped the timeout to 1ms.

At this point I just added a `Process.sleep(1)` and that also reliably made the error go away.

IMO this points to the operating system still holding onto the socket somehow - as you said.

I'm somewhat out of ideas, one thing I think we could still try is to set the SO_REUSEPORT option using the `raw` option on `inet:setopts/2`:  http://erlang.org/doc/man/inet.html#setopts-2

**Comment by visciang** [comment] 2017-09-17 14:30
Yes, I agree with you with you @MSch.
More than raw `SO_REUSEPORT` we can't do, did you give it a try?

**Comment by MSch** [comment] 2017-09-17 15:26
I just force-pushed to the branch again, and it seems `SO_REUSEPORT` indeed fixes the problem.

**Comment by mmacai** [comment] 2017-10-09 11:18
Any idea, when this might be in master?

**Comment by Cohen-Carlisle** [comment] 2018-02-15 20:12
I would love for a fix to this to get into master and be released. I'm currently using bypass but have to rerun tests often because of `{:error, :eaddrinuse}` .

**Closed** 2020-03-31 13:29 UTC
